name: 🚀 Deploy website on push

on:
  push:
    branches: [ deploy ]

jobs:
  deploy:
    name: 🚀 Deploy React
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Get latest code
        uses: actions/checkout@v3

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.REAL_FTP_SERVER }}
          username: ${{ secrets.REAL_FTP_USERNAME }}
          password: ${{ secrets.REAL_FTP_PASSWORD }}
          local-dir: dist/
          server-dir: public_html/
